site_title = "legged_paper_daily_arxiv"
limit_days = 7
cache_url = "https://linzhuyue.github.io/legged_paper_daily_arxiv/cache.json"

[[sources]]
limit = 150
category = "cs.RO"
title = "Robotics"

[[sources]]
limit = 150
category = "cs.AI"
title = "Artifical Intelligence"

[[sources]]
limit = 150
category = "cs.IR"
title = "Information Retrieval"

[[sources]]
limit = 150
category = "cs.LG"
title = "Machine Learning"

[[sources]]
limit = 150
category = "cs.OC"
title = "Optimization and Control"

[[sources]]
limit = 150
category = "cs.SY"
title = "Systems and Control"

[scripts]
highlight_title = "scripts/highlight_title.rhai"
highlight_author = "scripts/highlight_author.rhai"
highlight_conference = "scripts/highlight_conference.rhai"
